// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    Badge: typeof import('./src/components/Badge.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    ContactCard: typeof import('./src/components/ContactCard.vue')['default']
    DarkModeButton: typeof import('./src/components/DarkModeButton.vue')['default']
    HeroPresentation: typeof import('./src/components/HeroPresentation.vue')['default']
    InputElement: typeof import('./src/components/form/InputElement.vue')['default']
    NavigationBar: typeof import('./src/components/navigation/NavigationBar.vue')['default']
    NavLinks: typeof import('./src/components/navigation/NavLinks.vue')['default']
    NavSocialLinks: typeof import('./src/components/navigation/NavSocialLinks.vue')['default']
    ProjectCard: typeof import('./src/components/projects/ProjectCard.vue')['default']
    ProjectCards: typeof import('./src/components/projects/ProjectCards.vue')['default']
    ProjectFilters: typeof import('./src/components/projects/ProjectFilters.vue')['default']
    ProjectTags: typeof import('./src/components/projects/ProjectTags.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpeechCard: typeof import('./src/components/SpeechCard.vue')['default']
    SubmitButton: typeof import('./src/components/form/SubmitButton.vue')['default']
    TextAreaElement: typeof import('./src/components/form/TextAreaElement.vue')['default']
  }
}
