// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DarkModeButton: typeof import('./src/components/DarkModeButton.vue')['default']
    HeroPresentation: typeof import('./src/components/HeroPresentation.vue')['default']
    NavigationBar: typeof import('./src/components/navigation/NavigationBar.vue')['default']
    NavLinks: typeof import('./src/components/navigation/NavLinks.vue')['default']
    NavSocialLinks: typeof import('./src/components/navigation/NavSocialLinks.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
